In [7]:
import numpy as np
import matplotlib.pyplot as plt
import os

import cv2
import imutils
import imutils.perspective as persp # order the contour coordinates i.e. left, top, right, buttom
import scipy.spatial.distance as dist

In [14]:
# load images
img_dir = r'data/'
img = cv2.imread(os.path.join(img_dir, '1.jpeg')) # read in B G R order

# convert to R G B
rgb_img = cv2.cvtColor(img, cv2.COLOR_BAYER_BG2RGB)

# # show the image
# plt.figure(figsize=(15, 15))
# plt.show(rgb_img)


[[[127 164 186]
  [126 163 185]
  [126 163 185]
  ...
  [121 157 175]
  [116 152 170]
  [112 148 166]]

 [[127 164 186]
  [127 164 186]
  [126 163 185]
  ...
  [121 157 175]
  [116 152 170]
  [110 146 164]]

 [[127 164 186]
  [127 164 186]
  [127 164 186]
  ...
  [119 155 173]
  [114 150 168]
  [109 145 163]]

 ...

 [[ 96 124 148]
  [ 93 124 147]
  [ 94 122 146]
  ...
  [ 53  83 100]
  [ 52  82  99]
  [ 51  81  98]]

 [[ 93 120 141]
  [ 90 119 140]
  [ 91 118 139]
  ...
  [ 51  80  95]
  [ 51  80  95]
  [ 50  79  94]]

 [[ 90 117 138]
  [ 89 116 137]
  [ 88 115 136]
  ...
  [ 48  77  92]
  [ 49  78  93]
  [ 49  78  93]]]
